alter table public.pacientes
  add column if not exists fecha_nacimiento date,
  add column if not exists direccion text,
  add column if not exists contacto_2_nombre text,
  add column if not exists contacto_2_parentesco text,
  add column if not exists contacto_2_telefono text,
  add column if not exists contacto_2_direccion text,
  add column if not exists contacto_3_nombre text,
  add column if not exists contacto_3_parentesco text,
  add column if not exists contacto_3_telefono text,
  add column if not exists contacto_3_direccion text,
  add column if not exists observaciones_localizacion text;

create table if not exists public.sesiones_paciente (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  fecha_terapia date not null,
  reagendada boolean not null default false,
  fecha_reagenda date,
  fecha_pago date,
  cantidad numeric(10, 2),
  firma_data_url text,
  created_at timestamp with time zone not null default now()
);

alter table public.sesiones_paciente enable row level security;

create policy "Admin gestionar sesiones"
on public.sesiones_paciente
for all
to authenticated
using (true)
with check (true);

create table if not exists public.envios_reglamento (
  id bigint generated by default as identity primary key,
  paciente_id bigint not null references public.pacientes(id) on delete cascade,
  cita_id bigint not null references public.citas(id) on delete cascade,
  destinatario text,
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'enviado', 'error')),
  intentos integer not null default 0,
  ultimo_error text,
  enviado_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  unique (paciente_id)
);

alter table public.envios_reglamento enable row level security;

create policy "Admin gestionar envios reglamento"
on public.envios_reglamento
for all
to authenticated
using (true)
with check (true);

create or replace function public.registrar_cita_publica_v2(
  p_nombre_paciente text,
  p_edad integer,
  p_fecha_nacimiento date,
  p_nombre_responsable text,
  p_telefono text,
  p_correo text,
  p_direccion text,
  p_contacto_2_nombre text,
  p_contacto_2_parentesco text,
  p_contacto_2_telefono text,
  p_contacto_2_direccion text,
  p_contacto_3_nombre text,
  p_contacto_3_parentesco text,
  p_contacto_3_telefono text,
  p_contacto_3_direccion text,
  p_observaciones_localizacion text,
  p_servicio text,
  p_fecha date,
  p_hora time without time zone,
  p_motivo_consulta text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_paciente_id bigint;
  v_cita_id bigint;
  v_primera_cita boolean := false;
  v_hoy date := (current_timestamp at time zone 'America/Mexico_City')::date;
begin
  if length(trim(coalesce(p_nombre_paciente, ''))) < 2 then
    raise exception using errcode = '22023', message = 'El nombre del paciente no es valido.';
  end if;

  if coalesce(p_telefono, '') !~ '^[0-9]{10}$' then
    raise exception using errcode = '22023', message = 'El telefono debe contener 10 digitos.';
  end if;

  if p_fecha < v_hoy or extract(isodow from p_fecha) not between 1 and 6 then
    raise exception using errcode = '22023', message = 'La fecha no esta disponible.';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext(p_fecha::text));

  if exists (
    select 1
    from public.citas
    where fecha = p_fecha
      and estatus is distinct from 'Cancelada'
      and p_hora < hora + interval '1 hour'
      and p_hora + interval '1 hour' > hora
  ) then
    raise exception using errcode = '23P01', message = 'El horario ya no esta disponible.';
  end if;

  select id into v_paciente_id
  from public.pacientes
  where telefono = p_telefono
    and lower(trim(nombre_paciente)) = lower(trim(p_nombre_paciente))
  order by id
  limit 1;

  if v_paciente_id is null then
    v_primera_cita := true;

    insert into public.pacientes (
      nombre_paciente, edad, fecha_nacimiento, nombre_responsable, telefono,
      correo, direccion, contacto_2_nombre, contacto_2_parentesco,
      contacto_2_telefono, contacto_2_direccion, contacto_3_nombre,
      contacto_3_parentesco, contacto_3_telefono, contacto_3_direccion,
      observaciones_localizacion
    )
    values (
      trim(p_nombre_paciente), p_edad, p_fecha_nacimiento,
      nullif(trim(coalesce(p_nombre_responsable, '')), ''), p_telefono,
      nullif(trim(coalesce(p_correo, '')), ''),
      nullif(trim(coalesce(p_direccion, '')), ''),
      nullif(trim(coalesce(p_contacto_2_nombre, '')), ''),
      nullif(trim(coalesce(p_contacto_2_parentesco, '')), ''),
      nullif(trim(coalesce(p_contacto_2_telefono, '')), ''),
      nullif(trim(coalesce(p_contacto_2_direccion, '')), ''),
      nullif(trim(coalesce(p_contacto_3_nombre, '')), ''),
      nullif(trim(coalesce(p_contacto_3_parentesco, '')), ''),
      nullif(trim(coalesce(p_contacto_3_telefono, '')), ''),
      nullif(trim(coalesce(p_contacto_3_direccion, '')), ''),
      nullif(trim(coalesce(p_observaciones_localizacion, '')), '')
    )
    returning id into v_paciente_id;
  end if;

  insert into public.citas (
    nombre_paciente, edad, nombre_responsable, telefono, correo, servicio,
    modalidad, fecha, hora, motivo_consulta, estatus, confirmado,
    primera_consulta, paciente_id
  )
  values (
    trim(p_nombre_paciente), p_edad,
    nullif(trim(coalesce(p_nombre_responsable, '')), ''), p_telefono,
    nullif(trim(coalesce(p_correo, '')), ''), p_servicio, 'Presencial',
    p_fecha, p_hora, nullif(trim(coalesce(p_motivo_consulta, '')), ''),
    'Pendiente', false, v_primera_cita, v_paciente_id
  )
  returning id into v_cita_id;

  if v_primera_cita then
    insert into public.envios_reglamento (
      paciente_id, cita_id, destinatario
    )
    values (
      v_paciente_id, v_cita_id, nullif(trim(coalesce(p_correo, '')), '')
    )
    on conflict (paciente_id) do nothing;
  end if;

  return jsonb_build_object(
    'cita_id', v_cita_id,
    'paciente_id', v_paciente_id,
    'primera_cita', v_primera_cita
  );
end;
$function$;

revoke all on function public.registrar_cita_publica_v2(
  text, integer, date, text, text, text, text, text, text, text, text,
  text, text, text, text, text, text, date, time without time zone, text
) from public;

grant execute on function public.registrar_cita_publica_v2(
  text, integer, date, text, text, text, text, text, text, text, text,
  text, text, text, text, text, text, date, time without time zone, text
) to anon, authenticated;
