alter table public.app_profiles
  drop constraint if exists app_profiles_role_check;

alter table public.app_profiles
  add constraint app_profiles_role_check
  check (role in ('master_admin', 'admin', 'user'));

alter table public.invitaciones_usuario
  drop constraint if exists invitaciones_usuario_role_check;

alter table public.invitaciones_usuario
  add constraint invitaciones_usuario_role_check
  check (role in ('master_admin', 'admin', 'user'));

update public.app_profiles
set role = 'master_admin'
where id = (
  select id
  from public.app_profiles
  where role = 'admin'
  order by created_at
  limit 1
)
and not exists (
  select 1 from public.app_profiles where role = 'master_admin'
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $function$
  select
    not exists (
      select 1
      from public.app_profiles
      where role in ('master_admin', 'admin')
        and active
    )
    or exists (
      select 1
      from public.app_profiles
      where id = auth.uid()
        and role in ('master_admin', 'admin')
        and active
    );
$function$;

create or replace function public.is_master_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $function$
  select
    not exists (
      select 1
      from public.app_profiles
      where role = 'master_admin'
        and active
    )
    or exists (
      select 1
      from public.app_profiles
      where id = auth.uid()
        and role = 'master_admin'
        and active
    );
$function$;

create or replace function public.can_write()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $function$
  select public.is_admin();
$function$;

create or replace function public.can_manage_users()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $function$
  select public.is_master_admin();
$function$;

create or replace function public.registrar_invitacion_usuario(
  p_email text,
  p_role text
)
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $function$
declare
  v_id bigint;
begin
  if not public.can_manage_users() then
    raise exception using errcode = '42501', message = 'Solo el administrador maestro puede registrar usuarios.';
  end if;

  if coalesce(trim(p_email), '') !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception using errcode = '22023', message = 'El correo no es valido.';
  end if;

  if p_role not in ('master_admin', 'admin', 'user') then
    raise exception using errcode = '22023', message = 'El rol no es valido.';
  end if;

  insert into public.invitaciones_usuario (email, role, created_by, estado)
  values (lower(trim(p_email)), p_role, auth.uid(), 'pendiente')
  returning id into v_id;

  return v_id;
end;
$function$;

create or replace function public.actualizar_rol_usuario(
  p_user_id uuid,
  p_role text,
  p_active boolean
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $function$
begin
  if not public.can_manage_users() then
    raise exception using errcode = '42501', message = 'Solo el administrador maestro puede cambiar roles.';
  end if;

  if p_role not in ('master_admin', 'admin', 'user') then
    raise exception using errcode = '22023', message = 'El rol no es valido.';
  end if;

  update public.app_profiles
  set role = p_role,
      active = p_active,
      updated_at = now()
  where id = p_user_id;
end;
$function$;

drop policy if exists "Admins gestionar perfiles" on public.app_profiles;
create policy "Master gestionar perfiles"
on public.app_profiles
for all
to authenticated
using (public.can_manage_users())
with check (public.can_manage_users());

drop policy if exists "Admins gestionar invitaciones" on public.invitaciones_usuario;
create policy "Master gestionar invitaciones"
on public.invitaciones_usuario
for all
to authenticated
using (public.can_manage_users())
with check (public.can_manage_users());

create table if not exists public.galeria_terapias (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descripcion text,
  tipo text not null check (tipo in ('imagen', 'video')),
  ruta_archivo text not null,
  activo boolean not null default true,
  orden integer not null default 0,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.galeria_terapias enable row level security;

drop policy if exists galeria_publica_lectura on public.galeria_terapias;
create policy galeria_publica_lectura
on public.galeria_terapias
for select
to anon, authenticated
using (activo = true or public.can_write());

drop policy if exists galeria_admin_insert on public.galeria_terapias;
create policy galeria_admin_insert
on public.galeria_terapias
for insert
to authenticated
with check (public.can_write());

drop policy if exists galeria_admin_update on public.galeria_terapias;
create policy galeria_admin_update
on public.galeria_terapias
for update
to authenticated
using (public.can_write())
with check (public.can_write());

drop policy if exists galeria_admin_delete on public.galeria_terapias;
create policy galeria_admin_delete
on public.galeria_terapias
for delete
to authenticated
using (public.can_write());

insert into storage.buckets (id, name, public)
values ('galeria-terapias', 'galeria-terapias', true)
on conflict (id) do update set public = true;

drop policy if exists "Galeria publica lectura storage" on storage.objects;
create policy "Galeria publica lectura storage"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'galeria-terapias');

drop policy if exists "Galeria admin subir storage" on storage.objects;
create policy "Galeria admin subir storage"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'galeria-terapias' and public.can_write());

drop policy if exists "Galeria admin actualizar storage" on storage.objects;
create policy "Galeria admin actualizar storage"
on storage.objects
for update
to authenticated
using (bucket_id = 'galeria-terapias' and public.can_write())
with check (bucket_id = 'galeria-terapias' and public.can_write());

drop policy if exists "Galeria admin borrar storage" on storage.objects;
create policy "Galeria admin borrar storage"
on storage.objects
for delete
to authenticated
using (bucket_id = 'galeria-terapias' and public.can_write());

drop trigger if exists audit_galeria_terapias on public.galeria_terapias;
create trigger audit_galeria_terapias
after insert or update or delete on public.galeria_terapias
for each row execute function public.audit_table_change();

grant execute on function public.is_master_admin() to authenticated;
grant execute on function public.can_manage_users() to authenticated;
