alter table public.galeria_terapias
  add column if not exists publicacion_id uuid,
  add column if not exists likes_count integer not null default 0;

update public.galeria_terapias
set publicacion_id = gen_random_uuid()
where publicacion_id is null;

alter table public.galeria_terapias
  alter column publicacion_id set default gen_random_uuid(),
  alter column publicacion_id set not null;

create index if not exists galeria_terapias_publicacion_id_idx
  on public.galeria_terapias (publicacion_id);

create table if not exists public.galeria_likes (
  id bigint generated by default as identity primary key,
  publicacion_id uuid not null,
  visitante_id uuid not null,
  created_at timestamp with time zone not null default now(),
  unique (publicacion_id, visitante_id)
);

alter table public.galeria_likes enable row level security;

revoke all on public.galeria_likes from anon, authenticated;

create or replace function public.alternar_like_galeria(
  p_publicacion_id uuid,
  p_visitante_id uuid
)
returns table (
  liked boolean,
  likes_count integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_liked boolean;
  v_total integer;
begin
  if p_publicacion_id is null or p_visitante_id is null then
    raise exception 'Publicacion o visitante no valido';
  end if;

  if not exists (
    select 1
    from public.galeria_terapias
    where publicacion_id = p_publicacion_id
      and activo = true
  ) then
    raise exception 'Publicacion no disponible';
  end if;

  delete from public.galeria_likes
  where publicacion_id = p_publicacion_id
    and visitante_id = p_visitante_id;

  if found then
    v_liked := false;
  else
    insert into public.galeria_likes (publicacion_id, visitante_id)
    values (p_publicacion_id, p_visitante_id);
    v_liked := true;
  end if;

  select count(*)::integer
  into v_total
  from public.galeria_likes
  where publicacion_id = p_publicacion_id;

  update public.galeria_terapias
  set likes_count = v_total
  where publicacion_id = p_publicacion_id;

  return query select v_liked, v_total;
end;
$$;

revoke all on function public.alternar_like_galeria(uuid, uuid) from public;
grant execute on function public.alternar_like_galeria(uuid, uuid)
  to anon, authenticated;
