alter table public.pacientes
  add column if not exists activo boolean not null default true;

alter table public.sesiones_paciente
  add constraint sesiones_pago_requerido
  check (fecha_pago is not null and cantidad is not null and cantidad > 0) not valid;

alter table public.sesiones_paciente
  add constraint sesiones_reagenda_fecha_requerida
  check (reagendada is false or fecha_reagenda is not null) not valid;

create or replace function public.validar_sesion_paciente()
returns trigger
language plpgsql
set search_path = public
as $function$
begin
  if exists (
    select 1
    from public.sesiones_paciente
    where paciente_id = new.paciente_id
      and fecha_terapia = new.fecha_terapia
      and id is distinct from new.id
  ) then
    raise exception using
      errcode = '23505',
      message = 'Ya existe un registro para esa fecha de terapia.';
  end if;

  return new;
end;
$function$;

drop trigger if exists validar_sesion_paciente_unica on public.sesiones_paciente;
create trigger validar_sesion_paciente_unica
before insert or update on public.sesiones_paciente
for each row execute function public.validar_sesion_paciente();

create table if not exists public.app_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.invitaciones_usuario (
  id bigint generated by default as identity primary key,
  email text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'enviada', 'aceptada', 'cancelada')),
  created_by uuid references auth.users(id),
  created_at timestamp with time zone not null default now()
);

create table if not exists public.bitacora_cambios (
  id bigint generated by default as identity primary key,
  tabla text not null,
  registro_id text,
  accion text not null,
  usuario_id uuid references auth.users(id),
  usuario_email text,
  cambios jsonb,
  created_at timestamp with time zone not null default now()
);

alter table public.app_profiles enable row level security;
alter table public.invitaciones_usuario enable row level security;
alter table public.bitacora_cambios enable row level security;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $function$
begin
  insert into public.app_profiles (id, email, role)
  values (new.id, coalesce(new.email, ''), 'user')
  on conflict (id) do nothing;

  return new;
end;
$function$;

drop trigger if exists on_auth_user_created_app_profile on auth.users;
create trigger on_auth_user_created_app_profile
after insert on auth.users
for each row execute function public.handle_new_auth_user();

insert into public.app_profiles (id, email, role)
select
  u.id,
  coalesce(u.email, ''),
  case
    when not exists (
      select 1 from public.app_profiles p where p.role = 'admin'
    ) then 'admin'
    else 'user'
  end
from auth.users u
on conflict (id) do nothing;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $function$
  select
    not exists (select 1 from public.app_profiles where role = 'admin' and active)
    or exists (
      select 1
      from public.app_profiles
      where id = auth.uid()
        and role = 'admin'
        and active
    );
$function$;

create or replace function public.can_write()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $function$
  select public.is_admin();
$function$;

create or replace function public.registrar_invitacion_usuario(
  p_email text,
  p_role text
)
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $function$
declare
  v_id bigint;
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'Solo un administrador puede registrar usuarios.';
  end if;

  if coalesce(trim(p_email), '') !~* '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
    raise exception using errcode = '22023', message = 'El correo no es valido.';
  end if;

  if p_role not in ('admin', 'user') then
    raise exception using errcode = '22023', message = 'El rol no es valido.';
  end if;

  insert into public.invitaciones_usuario (email, role, created_by)
  values (lower(trim(p_email)), p_role, auth.uid())
  returning id into v_id;

  return v_id;
end;
$function$;

create or replace function public.actualizar_rol_usuario(
  p_user_id uuid,
  p_role text,
  p_active boolean
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $function$
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'Solo un administrador puede cambiar roles.';
  end if;

  if p_role not in ('admin', 'user') then
    raise exception using errcode = '22023', message = 'El rol no es valido.';
  end if;

  update public.app_profiles
  set role = p_role,
      active = p_active,
      updated_at = now()
  where id = p_user_id;
end;
$function$;

create or replace function public.audit_table_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $function$
declare
  v_email text;
  v_record_id text;
  v_changes jsonb;
begin
  select email into v_email
  from auth.users
  where id = auth.uid();

  if tg_op = 'DELETE' then
    v_record_id := coalesce(to_jsonb(old)->>'id', null);
    v_changes := jsonb_build_object('old', to_jsonb(old));
  elsif tg_op = 'UPDATE' then
    v_record_id := coalesce(to_jsonb(new)->>'id', to_jsonb(old)->>'id');
    v_changes := jsonb_build_object('old', to_jsonb(old), 'new', to_jsonb(new));
  else
    v_record_id := coalesce(to_jsonb(new)->>'id', null);
    v_changes := jsonb_build_object('new', to_jsonb(new));
  end if;

  insert into public.bitacora_cambios (
    tabla,
    registro_id,
    accion,
    usuario_id,
    usuario_email,
    cambios
  )
  values (
    tg_table_name,
    v_record_id,
    tg_op,
    auth.uid(),
    v_email,
    v_changes
  );

  return coalesce(new, old);
end;
$function$;

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'pacientes',
    'citas',
    'paciente_detalle',
    'expedientes',
    'paciente_objetivos',
    'objetivos_terapeuticos',
    'archivos_paciente',
    'sesiones_paciente'
  ]
  loop
    execute format('drop trigger if exists audit_%I on public.%I', v_table, v_table);
    execute format(
      'create trigger audit_%I after insert or update or delete on public.%I for each row execute function public.audit_table_change()',
      v_table,
      v_table
    );
  end loop;
end $$;

create policy "Usuarios ver perfiles"
on public.app_profiles
for select
to authenticated
using (true);

create policy "Admins gestionar perfiles"
on public.app_profiles
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Admins gestionar invitaciones"
on public.invitaciones_usuario
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Usuarios ver bitacora"
on public.bitacora_cambios
for select
to authenticated
using (true);

create or replace function public.eliminar_paciente_admin(p_paciente_id bigint)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  v_archivado integer;
begin
  if not public.is_admin() then
    raise exception using errcode = '42501', message = 'Solo un administrador puede archivar pacientes.';
  end if;

  update public.pacientes
  set activo = false
  where id = p_paciente_id;

  get diagnostics v_archivado = row_count;

  update public.citas
  set estatus = 'Cancelada',
      confirmado = false
  where paciente_id = p_paciente_id
    and estatus is distinct from 'Cancelada';

  if v_archivado = 0 then
    raise exception using errcode = 'P0002', message = 'El paciente no existe.';
  end if;
end;
$function$;

grant execute on function public.registrar_invitacion_usuario(text, text) to authenticated;
grant execute on function public.actualizar_rol_usuario(uuid, text, boolean) to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.can_write() to authenticated;

do $$
declare
  v_table text;
  v_policy record;
begin
  foreach v_table in array array[
    'pacientes',
    'citas',
    'paciente_detalle',
    'expedientes',
    'paciente_objetivos',
    'objetivos_terapeuticos',
    'archivos_paciente',
    'sesiones_paciente',
    'envios_reglamento'
  ]
  loop
    if to_regclass(format('public.%I', v_table)) is not null then
      execute format('alter table public.%I enable row level security', v_table);

      for v_policy in
        select policyname
        from pg_policies
        where schemaname = 'public'
          and tablename = v_table
      loop
        execute format(
          'drop policy if exists %I on public.%I',
          v_policy.policyname,
          v_table
        );
      end loop;

      execute format(
        'create policy %I on public.%I for select to authenticated using (true)',
        v_table || '_lectura_autenticada',
        v_table
      );

      execute format(
        'create policy %I on public.%I for insert to authenticated with check (public.can_write())',
        v_table || '_insert_admin',
        v_table
      );

      execute format(
        'create policy %I on public.%I for update to authenticated using (public.can_write()) with check (public.can_write())',
        v_table || '_update_admin',
        v_table
      );

      execute format(
        'create policy %I on public.%I for delete to authenticated using (public.can_write())',
        v_table || '_delete_admin',
        v_table
      );
    end if;
  end loop;
end $$;

create or replace function public.reactivar_paciente_con_cita()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  if new.paciente_id is not null then
    update public.pacientes
    set activo = true
    where id = new.paciente_id;
  end if;

  return new;
end;
$function$;

drop trigger if exists reactivar_paciente_con_cita on public.citas;
create trigger reactivar_paciente_con_cita
after insert on public.citas
for each row execute function public.reactivar_paciente_con_cita();
